"""Reproducible API/schema documentation; no database connection required."""

import argparse
import json
from pathlib import Path

from pydantic import SecretStr
from sqlalchemy import CheckConstraint, ForeignKeyConstraint
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql.schema import ColumnCollectionConstraint

import aegis_api.auth_models  # noqa: F401
from aegis_api.conventions import (
    Collection,
    ErrorResponse,
    EventQuery,
    EventSummary,
    FindingQuery,
    FindingSummary,
)
from aegis_api.db.models import Base
from aegis_api.main import create_app
from aegis_api.settings import Settings


def documents() -> dict[str, str]:
    config = Settings(
        profile="test",
        database_url=SecretStr("postgresql+asyncpg://schema@localhost/schema"),
        redis_url=SecretStr("redis://localhost/0"),
    )
    from aegis_api.reporting import Snapshot

    schemas = {
        "ReportSnapshot": Snapshot.model_json_schema(),
        "ErrorResponse": ErrorResponse.model_json_schema(),
        "FindingQuery": FindingQuery.model_json_schema(),
        "EventQuery": EventQuery.model_json_schema(),
        "FindingCollection": Collection[FindingSummary].model_json_schema(),
        "EventCollection": Collection[EventSummary].model_json_schema(),
    }
    dialect = postgresql.dialect()  # type: ignore[no-untyped-call]
    lines = [
        "# Generated PostgreSQL schema",
        "",
        "Generated by `python -m aegis_api.schema_docs`. "
        "Migrations 0001–0010 own DDL and triggers. "
        "Models are private persistence records, never response schemas.",
        "",
    ]
    for table in Base.metadata.sorted_tables:
        lines.extend(
            [
                f"## {table.name}",
                "",
                "| Column | PostgreSQL type | Nullable |",
                "| --- | --- | --- |",
            ]
        )
        for column in table.columns:
            sql_type = column.type.compile(dialect=dialect)
            nullable = "yes" if column.nullable else "no"
            lines.append(f"| {column.name} | {sql_type} | {nullable} |")
        lines.extend(["", "Constraints and indexes:", ""])
        for constraint in sorted(table.constraints, key=lambda c: str(c.name)):
            description = (
                ", ".join(c.name for c in constraint.columns)
                if isinstance(constraint, ColumnCollectionConstraint)
                else ""
            )
            if isinstance(constraint, ForeignKeyConstraint):
                description += (
                    " → "
                    + ", ".join(e.target_fullname for e in constraint.elements)
                    + f"; ON DELETE {constraint.ondelete}"
                )
            if isinstance(constraint, CheckConstraint):
                description = str(constraint.sqltext)
            lines.append(
                f"- `{constraint.name}`: {type(constraint).__name__}; {description}"
            )
        for index in sorted(table.indexes, key=lambda i: str(i.name)):
            lines.append(
                f"- `{index.name}`: index ({', '.join(c.name for c in index.columns)})"
            )
        lines.append("")
    return {
        "openapi.json": json.dumps(
            create_app(config).openapi(), indent=2, sort_keys=True
        )
        + "\n",
        "conventions.schema.json": json.dumps(schemas, indent=2, sort_keys=True) + "\n",
        "database-schema.md": "\n".join(lines),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=Path("docs/generated"))
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated = documents()
    if args.check:
        drift = [
            name
            for name, content in generated.items()
            if not (args.output / name).exists()
            or (args.output / name).read_text() != content
        ]
        if drift:
            raise SystemExit(
                "Generated schema documentation differs: " + ", ".join(drift)
            )
    else:
        args.output.mkdir(parents=True, exist_ok=True)
        for name, content in generated.items():
            (args.output / name).write_text(content)


if __name__ == "__main__":
    main()
