import { z } from 'zod';
export const credentialSchema = z.object({
  id: z.string(),
  auth_type: z.string(),
  header_name: z.string(),
  masked: z.string(),
  version: z.number(),
  revoked: z.boolean(),
});
export const targetSchema = z.object({
  id: z.string(),
  project_id: z.string(),
  display_name: z.string(),
  kind: z.string(),
  base_url: z.string(),
  environment: z.string(),
  policy_id: z.string().nullable(),
  consent_at: z.string().nullable(),
  authorization_owner_id: z.string().nullable(),
  authorization_declaration: z.string(),
  inclusion_patterns: z.array(z.string()),
  exclusion_patterns: z.array(z.string()),
  allowed_methods: z.array(z.string()),
  rate_limit: z.number(),
  timeout_seconds: z.number(),
  status: z.string(),
  version: z.number(),
  verified_at: z.string().nullable(),
  has_openapi: z.boolean(),
  credentials: z.array(credentialSchema),
});
export const policySchema = z.object({
  id: z.string(),
  name: z.string(),
  version: z.number(),
  mode: z.enum(['baseline', 'passive', 'active']),
  max_duration_seconds: z.number(),
  max_requests: z.number(),
  max_depth: z.number(),
  spider: z.enum(['none', 'traditional', 'ajax']),
  active_rule_allowlist: z.array(z.string()),
  rate_limit: z.number(),
  excluded_paths: z.array(z.string()),
  fail_severity: z.string(),
  warn_severity: z.string(),
  allow_private: z.boolean(),
  internal_test_declaration: z.string(),
  active_warning_acknowledged: z.boolean(),
});
